sudo: true
language: go

notifications:
  email:
    - dextrackmedia@gmail.com

before_install:
  - git submodule update --init --recursive

install:
  - export GOPATH=$PWD

script: go build

go:
  - 1.4.2
